insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Jello - Assorted', 857.83);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Scallop - St. Jaques', 672.78);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Turkey - Whole, Fresh', 122.25);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Fuji Apples', 527.67);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Durian Fruit', 67.22);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Mangoes', 493.11);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Garam Masala Powder', 354.31);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Currants', 686.66);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Spring Roll Veg Mini', 48.24);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Orange Roughy 4/6 Oz', 318.97);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Bread - Onion Focaccia', 483.86);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pastry - Butterscotch Baked', 538.08);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cabbage - Red', 892.97);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Remy Red', 505.01);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Longos - Chicken Wings', 419.26);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pastry - French Mini Assorted', 826.49);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Nut - Almond, Blanched, Whole', 438.56);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Bread - Italian Corn Meal Poly', 428.32);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Beans - Long, Chinese', 928.48);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Sour Cream', 822.89);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Jolt Cola', 79.11);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Juice - Pineapple, 48 Oz', 672.41);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Turnip - White, Organic', 664.58);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Seedlings - Clamshell', 321.12);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Leeks - Baby, White', 597.21);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Tea - Decaf Lipton', 976.42);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Chicken - Livers', 406.5);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Laundry - Bag Cloth', 790.33);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Clams - Canned', 465.89);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Red, Black Opal Shiraz', 224.21);
